artifact_uri: runs\mlflow/1/164bc762aaa1404ca4fbb8250e547e22/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 164bc762aaa1404ca4fbb8250e547e22
run_uuid: 164bc762aaa1404ca4fbb8250e547e22
source_name: ''
source_type: 4
source_version: ''
start_time: 1708886464210
status: 1
tags: []
user_id: Bárbara Z
