artifact_uri: runs\mlflow/1/5ee38a38ee10428aac17c632301cbe97/artifacts
end_time: 1708915013641
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5ee38a38ee10428aac17c632301cbe97
run_uuid: 5ee38a38ee10428aac17c632301cbe97
source_name: ''
source_type: 4
source_version: ''
start_time: 1708913797454
status: 3
tags: []
user_id: Bárbara Z
